/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juegodeturnos;
import javax.swing.JOptionPane;

/**
 *
 * @author Frances
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        pb_vida1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnatacar1 = new javax.swing.JButton();
        btnatacar2 = new javax.swing.JButton();
        pb_vida2 = new javax.swing.JProgressBar();
        lbl_ganador = new javax.swing.JLabel();
        resetbar1 = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        curar2 = new javax.swing.JButton();
        curar1 = new javax.swing.JButton();
        btnataqueespecial1 = new javax.swing.JButton();
        btnataqueespecial2 = new javax.swing.JButton();
        btnfuego = new javax.swing.JButton();
        btnflechita = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pb_vida1.setValue(100);
        pb_vida1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pb_vida1MousePressed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Frances\\Documents\\NetBeansProjects\\juegodeturnos\\descarga (1).png")); // NOI18N
        jLabel1.setText("Jugador1");

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Frances\\Documents\\NetBeansProjects\\juegodeturnos\\descarga.png")); // NOI18N
        jLabel2.setText("Jugador2");

        btnatacar1.setText("Atacar");
        btnatacar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnatacar1MousePressed(evt);
            }
        });
        btnatacar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnatacar1ActionPerformed(evt);
            }
        });

        btnatacar2.setText("Atacar");
        btnatacar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnatacar2MousePressed(evt);
            }
        });
        btnatacar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnatacar2ActionPerformed(evt);
            }
        });

        pb_vida2.setValue(100);

        lbl_ganador.setText("AssasinKnight");

        resetbar1.setText("RESET");
        resetbar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbar1ActionPerformed(evt);
            }
        });

        salir.setText("SALIR");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        curar2.setText("Curar");
        curar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                curar2MousePressed(evt);
            }
        });
        curar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                curar2ActionPerformed(evt);
            }
        });

        curar1.setText("Curar");
        curar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                curar1MousePressed(evt);
            }
        });
        curar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                curar1ActionPerformed(evt);
            }
        });

        btnataqueespecial1.setText("Ataque Especial");
        btnataqueespecial1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnataqueespecial1MousePressed(evt);
            }
        });
        btnataqueespecial1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnataqueespecial1ActionPerformed(evt);
            }
        });

        btnataqueespecial2.setText("Ataque Especial");
        btnataqueespecial2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnataqueespecial2MousePressed(evt);
            }
        });

        btnfuego.setText("Bolita de fuego");
        btnfuego.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnfuegoMousePressed(evt);
            }
        });

        btnflechita.setText("Flechita");
        btnflechita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnflechitaMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pb_vida1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pb_vida2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnatacar1)
                .addGap(18, 18, 18)
                .addComponent(curar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(curar2)
                .addGap(18, 18, 18)
                .addComponent(btnatacar2)
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_ganador)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(resetbar1)
                        .addGap(18, 18, 18)
                        .addComponent(salir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnataqueespecial1)
                    .addComponent(btnfuego))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnataqueespecial2)
                    .addComponent(btnflechita))
                .addGap(76, 76, 76))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lbl_ganador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pb_vida1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pb_vida2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnatacar1)
                    .addComponent(btnatacar2)
                    .addComponent(curar2)
                    .addComponent(curar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnataqueespecial1)
                    .addComponent(btnataqueespecial2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnfuego)
                    .addComponent(btnflechita))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetbar1)
                    .addComponent(salir))
                .addGap(73, 73, 73))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnatacar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnatacar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnatacar1ActionPerformed

    private void btnatacar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnatacar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnatacar2ActionPerformed

    private void btnatacar1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnatacar1MousePressed
        int vida2=pb_vida2.getValue();
        int random=(int)(Math.random()*1000%10);
        vida2-=10+random;
        System.out.println(10+random);
        pb_vida2.setValue(vida2);
        disipar1();
        if(vida2<=0){
            JOptionPane.showMessageDialog(pb_vida2, "Caballero de Hierro\n\t Has Perdido");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnatacar1MousePressed

    private void pb_vida1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pb_vida1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_pb_vida1MousePressed

    private void btnatacar2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnatacar2MousePressed
        int vida1=pb_vida1.getValue();
        vida1-=10;
        pb_vida1.setValue(vida1); 
        
        disipar2();
        
        if(vida1<=0)
            JOptionPane.showMessageDialog(pb_vida1, "Dragon Has Perdido");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnatacar2MousePressed

    private void resetbar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbar1ActionPerformed
        // TODO add your handling code here:
        pb_vida1.setValue(100);
        pb_vida2.setValue(100);
        btnatacar1.setVisible(true);
        btnatacar2.setVisible(true);
        
    }//GEN-LAST:event_resetbar1ActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void curar2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_curar2MousePressed
int salud2 = pb_vida2.getValue();
int curar2 = salud2+10;
pb_vida2.setValue(curar2);

disipar6();
// TODO add your handling code here:
    }//GEN-LAST:event_curar2MousePressed

    private void curar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_curar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_curar2ActionPerformed

    private void curar1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_curar1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_curar1MousePressed

    private void curar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_curar1ActionPerformed
int salud1 = pb_vida1.getValue();
int curar1 = salud1+10;
pb_vida1.setValue(curar1);

disipar5();
// TODO add your handling code here:
    }//GEN-LAST:event_curar1ActionPerformed

    private void btnataqueespecial1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnataqueespecial1MousePressed
        int vida2=pb_vida2.getValue();
        double x =(int)30*Math.random()+1;
        vida2-=(int)x;
        pb_vida2.setValue(vida2); 
        
              
       
        disipar3();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnataqueespecial1MousePressed

    private void btnataqueespecial1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnataqueespecial1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnataqueespecial1ActionPerformed

    private void btnataqueespecial2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnataqueespecial2MousePressed
        int vida1=pb_vida1.getValue();
        double x =(int)30*Math.random()+1;
        vida1-=(int)x;
        pb_vida1.setValue(vida1);
        
        disipar4();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnataqueespecial2MousePressed

    private void btnfuegoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnfuegoMousePressed
    int vida2=pb_vida2.getValue();
        vida2-=1; //+ Math.random()*1;
        pb_vida2.setValue(vida2); 


// TODO add your handling code here:
    }//GEN-LAST:event_btnfuegoMousePressed

    private void btnflechitaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnflechitaMousePressed
int vida1=pb_vida1.getValue();
        vida1-=1; //+ Math.random()*30;
        pb_vida1.setValue(vida1);        // TODO add your handling code here:
    }//GEN-LAST:event_btnflechitaMousePressed
    
    private void disipar1(){
        btnatacar1.setVisible(false);
        btnatacar2.setVisible(true);
        curar2.setVisible(true);
        curar1.setVisible(false);
    }
    
    private void disipar2(){
        btnatacar1.setVisible(true);
        btnatacar2.setVisible(false);
        curar1.setVisible(true);
        curar2.setVisible(false);
    }
     private void disipar3(){
        btnataqueespecial1.setVisible(false);
       // btnataqueespecial2.setVisible(true);
    }
      private void disipar4(){
        //btnataqueespecial1.setVisible(true);
        btnataqueespecial2.setVisible(false);
    }
  
      private void disipar5(){
        curar2.setVisible(true);
        curar1.setVisible(false);
        btnatacar1.setVisible(false);
        btnatacar2.setVisible(true);
    }
      private void disipar6(){
        curar1.setVisible(true);
        curar2.setVisible(false);
        btnatacar1.setVisible(true);
        btnatacar2.setVisible(false);
    } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnatacar1;
    private javax.swing.JButton btnatacar2;
    private javax.swing.JButton btnataqueespecial1;
    private javax.swing.JButton btnataqueespecial2;
    private javax.swing.JButton btnflechita;
    private javax.swing.JButton btnfuego;
    private javax.swing.JButton curar1;
    private javax.swing.JButton curar2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl_ganador;
    private javax.swing.JProgressBar pb_vida1;
    private javax.swing.JProgressBar pb_vida2;
    private javax.swing.JButton resetbar1;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
